### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'CellProfiler==3.1.9' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by mWekking** [Scotchman0/CellProfiler_Ubuntu_Installer#6]
After full installation completes, the app cant launch and I have no idea why? Everything else seems to go right

Successfully installed botocore-1.20.88
./CellProfiler_Install.sh: line 179: cd: /home/mark/Cellprofiler/plugins: No such file or directory
Cellprofiler should now launch - may take a few moments for initialization...
Don't forget to submit bugs via the git page and make adjustments/pulls as you see fit, generally I'll push them
relatively swiftly... Cheers.
if cellprofiler starts - I HIGHLY recommend a restart before you dive in.
Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'CellProfiler==3.1.9' distribution was not found and is required by the application

**Comment by Scotchman0** [comment]
Hey! Weird. 

I'm trying to replicate your issue presently. In the meantime can you provide the following outputs:

$ sudo pip freeze
$ cat /etc/*release
$ python3 -V
$ sudo sed -n '770,780p' /usr/local/lib/python3.6/dist-packages/pkg_resources/init.py

Thanks!

**Comment by Scotchman0** [comment]
as a follow up inquiry - I note:  ./CellProfiler_Install.sh: line 179: cd: /home/mark/Cellprofiler/plugins: No such file or directory
did you run the installer with sudo priviliges? Might have failed somewhere in the pipeline without permission to properly clone the baseline setup or build a directory. You should be able to rerun: $ sudo ./CellProfiler_Install.sh to ensure things are where they should be if you didn't run with adequate permissions first.

**Comment by Scotchman0** [comment]
I observed that the acquisition step doesn't correctly swap branches to v3.1.9 the way it should. I'll patch this shortly so future installs won't hang, In the meantime you should be able to correct this by running the following:

$ cd ~/CellProfiler
$ sudo git stash (this will let you move branches)
$ sudo git checkout v3.1.9
$ sudo nano ~/CellProfiler/setup.py --> line 93 --> change <=3.6.3 to <=3.6.9


$ sudo python3.6 -m pip install --editable .
$ cd ~/CellProfiler/plugins && git clone https://github.com/CellProfiler/Cellprofiler-Plugins
$ mv ~/CellProfiler/plugins/Cellprofiler-Plugins/* ~/CellProfiler/plugins/
$ cd ~/CellProfiler/plugins && cp classifypixelsunet.py ~/CellProfiler/cellprofiler/modules
$ cp /tmp/cellprofilerstuff/* ~/CellProfiler/cellprofiler/modules/
$ cd ~/Cellprofiler/plugins && sudo pip install requirements.txt

then launch with 
$ sudo cellprofiler

I'll need a little longer to validate my changes (the VM I'm running on is potato speed compiling WXPython, so I may update again later with another fix but let me know if this doesn't resolve). Next release candidate should do all this automatically once I validate this but figure this way you can give it a shot while I work on the overall issue.

**Comment by Scotchman0** [comment]
well the good news is that I've validated your bug. The bad news is I've opened a whole host of other issues that now need to be addressed to actually get this back into production status. 

Keep an eye here for when there's next an update - will be working on this for a bit. Thanks for bringing it to my attention. There's a number of requirement modifications that will need to be made to the baseline script to be compatible with some of the changes that were implemented with the cellprofiler branch awhile ago, and more than a few variances.

**Comment by mWekking** [comment]
Thanks you very much for the quick response and so extensive! Sadly your solution posted above doesn't seem to work while trying to cp the plugins, I had issues with the directories I wanted to copy to not being empty and not able to copy 
 Classifypixelsunet.py, when I run sudo cellprofiler:

Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 33, in <module>
    sys.exit(load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')())
  File "/usr/local/bin/cellprofiler", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 93, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mark/CellProfiler/cellprofiler/__main__.py", line 13, in <module>
    import bioformats.formatreader
  File "/usr/local/lib/python3.6/dist-packages/bioformats/__init__.py", line 21, in <module>
    import javabridge
  File "/usr/local/lib/python3.6/dist-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/usr/local/lib/python3.6/dist-packages/javabridge/jutil.py", line 162, in <module>
    import javabridge._javabridge as _javabridge
  File "__init__.pxd", line 918, in init _javabridge
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by Scotchman0** [comment]
Sorry for the delay on this issue - I appreciate your patience! I'm rebuilding a new branch under develop which will be merged with main after I resolve the issues you are experiencing here. I have discovered a chain of issues that initiate from a number of inconsistencies. I've let this project lapse for awhile so it's a bit more out of date than I thought. I'm hoping to have a resolution for you shortly, as this impacts all new users at present. Hopefully in the next few days. Thanks!

**Comment by Scotchman0** [comment]
Good morning - still broken on my end. I'm going to refer you to the official repository's conda installation path solution which may resolve your issues faster than I'll be able to patch this build: https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation

I will still update here when available but if you have a project and need something running now, this should resolve ^

thanks!

**Comment by mWekking** [comment]
This conda installation did eventually work! thanks for the help

**Comment by Scotchman0** [comment]
Thanks for the update! Glad to hear it.
